### ISSUE TITLE
A new category for renders

### ISSUE THREAD

**Issue by jonathanwestin** [CDH-DevTeam/sodrarada-gui#11]
I would like to keep the panoramas out of the gallery-view, and none of the categories really fit that object type, so if we create a new category called "renders", then the problem would be solved.

**Comment by jonathanwestin** [comment]
Just realized I can simply avoid giving these a category

**Comment by arildm** [comment]
There is a field for selecting whether an image is panorama or not. Here's an example where it is "on": https://sodrarada.dh.gu.se/api/admin/plugins/content-manager/collectionType/application::image.image/107 So we can still easily show them separately if we want?

**Comment by jonathanwestin** [comment]
Yes, but i was thinking also of renders that are not panoramas, but I will simply mark them as having no category.
