### ISSUE TITLE
The Se Alla-button

### ISSUE THREAD

**Issue by jonathanwestin** [CDH-DevTeam/sodrarada-gui#4]
The button should hide all other columns and expand the particular column to a gallery view (i.e use the available width of the page and display images in rows)and then load all the photos (these should now have been loaded in column view cause that could be brutal). A close button should appear to bring back column view.

![galleryview](https://user-images.githubusercontent.com/70022179/168760121-34619ac0-6d25-4b60-b787-229109c3035c.jpg)
.

**Comment by arildm** [comment]
Fixed in e9b75e1 and 254c2d4
